const std = @import("std");
const Builder = std.Build;
const Target = std.Target;
const Feature = std.Target.Cpu.Feature;

pub fn build(b: *Builder) void {
    const features = Target.x86.Feature;

    var disabled_features = Feature.Set.empty;
    var enabled_features = Feature.Set.empty;

    disabled_features.addFeature(@intFromEnum(features.mmx));
    disabled_features.addFeature(@intFromEnum(features.sse));
    disabled_features.addFeature(@intFromEnum(features.sse2));
    disabled_features.addFeature(@intFromEnum(features.avx));
    disabled_features.addFeature(@intFromEnum(features.avx2));
    enabled_features.addFeature(@intFromEnum(features.soft_float));

    const target = b.resolveTargetQuery(Target.Query{
        .cpu_arch = Target.Cpu.Arch.x86,
        .os_tag = Target.Os.Tag.linux,
        .abi = Target.Abi.musl,
        .cpu_features_sub = disabled_features,
        .cpu_features_add = enabled_features,
    });

    const userModule = b.addModule(
        "doomgeneric",
        .{
            .optimize = .ReleaseSmall,
            .target = target,
            .link_libc = true,
            .single_threaded = true,
        },
    );

    const userExe = b.addExecutable(.{
        .name = "doomgeneric.elf",
        .root_module = userModule,
    });
    userExe.setLinkerScript(b.path("doomgeneric/linker.ld"));

    userExe.addCSourceFiles(.{
        .files = &cSources,
        .flags = &[_][]const u8{
            "-static",
            "-Wall",
            "-O2",
            "-ggdb3",
            "-g",
            "-DDOOMGENERIC_RESX=640",
            "-DDOOMGENERIC_RESY=400",
        },
        .language = .c,
    });
    userExe.addIncludePath(b.path("doomgeneric/"));

    b.addNamedLazyPath("doom1.wad", b.path("doom1.wad"));
    b.installArtifact(userExe);
}

const cSources = [_][]const u8{
    "doomgeneric/NyaOSstdio.c",

    "doomgeneric/dummy.c",
    "doomgeneric/am_map.c",
    "doomgeneric/doomdef.c",
    "doomgeneric/doomstat.c",
    "doomgeneric/dstrings.c",
    "doomgeneric/d_event.c",
    "doomgeneric/d_items.c",
    "doomgeneric/d_iwad.c",
    "doomgeneric/d_loop.c",
    "doomgeneric/d_main.c",
    "doomgeneric/d_mode.c",
    "doomgeneric/d_net.c",
    "doomgeneric/f_finale.c",
    "doomgeneric/f_wipe.c",
    "doomgeneric/g_game.c",
    "doomgeneric/hu_lib.c",
    "doomgeneric/hu_stuff.c",
    "doomgeneric/info.c",
    "doomgeneric/i_cdmus.c",
    "doomgeneric/i_endoom.c",
    "doomgeneric/i_joystick.c",
    "doomgeneric/i_scale.c",
    "doomgeneric/i_sound.c",
    "doomgeneric/i_system.c",
    "doomgeneric/i_timer.c",
    "doomgeneric/memio.c",
    "doomgeneric/m_argv.c",
    "doomgeneric/m_bbox.c",
    "doomgeneric/m_cheat.c",
    "doomgeneric/m_config.c",
    "doomgeneric/m_controls.c",
    "doomgeneric/m_fixed.c",
    "doomgeneric/m_menu.c",
    "doomgeneric/m_misc.c",
    "doomgeneric/m_random.c",
    "doomgeneric/p_ceilng.c",
    "doomgeneric/p_doors.c",
    "doomgeneric/p_enemy.c",
    "doomgeneric/p_floor.c",
    "doomgeneric/p_inter.c",
    "doomgeneric/p_lights.c",
    "doomgeneric/p_map.c",
    "doomgeneric/p_maputl.c",
    "doomgeneric/p_mobj.c",
    "doomgeneric/p_plats.c",
    "doomgeneric/p_pspr.c",
    "doomgeneric/p_saveg.c",
    "doomgeneric/p_setup.c",
    "doomgeneric/p_sight.c",
    "doomgeneric/p_spec.c",
    "doomgeneric/p_switch.c",
    "doomgeneric/p_telept.c",
    "doomgeneric/p_tick.c",
    "doomgeneric/p_user.c",
    "doomgeneric/r_bsp.c",
    "doomgeneric/r_data.c",
    "doomgeneric/r_draw.c",
    "doomgeneric/r_main.c",
    "doomgeneric/r_plane.c",
    "doomgeneric/r_segs.c",
    "doomgeneric/r_sky.c",
    "doomgeneric/r_things.c",
    "doomgeneric/sha1.c",
    "doomgeneric/sounds.c",
    "doomgeneric/statdump.c",
    "doomgeneric/st_lib.c",
    "doomgeneric/st_stuff.c",
    "doomgeneric/s_sound.c",
    "doomgeneric/tables.c",
    "doomgeneric/v_video.c",
    "doomgeneric/wi_stuff.c",
    "doomgeneric/w_checksum.c",
    "doomgeneric/w_file.c",
    "doomgeneric/w_main.c",
    "doomgeneric/w_wad.c",
    "doomgeneric/z_zone.c",
    "doomgeneric/w_file_stdc.c",
    "doomgeneric/i_input.c",
    "doomgeneric/i_video.c",
    "doomgeneric/doomgeneric.c",
    "doomgeneric/doomgeneric_NyaOS.c",
};
const hFiles = [_][]const u8{
    "doomgeneric/NyaOSstdio.h",

    "doomgeneric/am_map.h",
    "doomgeneric/config.h",
    "doomgeneric/deh_main.h",
    "doomgeneric/deh_misc.h",
    "doomgeneric/deh_str.h",
    "doomgeneric/d_englsh.h",
    "doomgeneric/d_event.h",
    "doomgeneric/d_items.h",
    "doomgeneric/d_iwad.h",
    "doomgeneric/d_loop.h",
    "doomgeneric/d_main.h",
    "doomgeneric/d_mode.h",
    "doomgeneric/doomdata.h",
    "doomgeneric/doomdef.h",
    "doomgeneric/doomfeatures.h",
    "doomgeneric/doomgeneric.h",
    "doomgeneric/doom.h",
    "doomgeneric/doomkeys.h",
    "doomgeneric/doomstat.h",
    "doomgeneric/doomtype.h",
    "doomgeneric/d_player.h",
    "doomgeneric/dstrings.h",
    "doomgeneric/d_textur.h",
    "doomgeneric/d_think.h",
    "doomgeneric/d_ticcmd.h",
    "doomgeneric/f_finale.h",
    "doomgeneric/f_wipe.h",
    "doomgeneric/g_game.h",
    "doomgeneric/gusconf.h",
    "doomgeneric/hu_lib.h",
    "doomgeneric/hu_stuff.h",
    "doomgeneric/i_cdmus.h",
    "doomgeneric/i_endoom.h",
    "doomgeneric/i_joystick.h",
    "doomgeneric/info.h",
    "doomgeneric/i_scale.h",
    "doomgeneric/i_sound.h",
    "doomgeneric/i_swap.h",
    "doomgeneric/i_system.h",
    "doomgeneric/i_timer.h",
    "doomgeneric/i_video.h",
    "doomgeneric/m_argv.h",
    "doomgeneric/m_bbox.h",
    "doomgeneric/m_cheat.h",
    "doomgeneric/m_config.h",
    "doomgeneric/m_controls.h",
    "doomgeneric/memio.h",
    "doomgeneric/m_fixed.h",
    "doomgeneric/m_menu.h",
    "doomgeneric/m_misc.h",
    "doomgeneric/m_random.h",
    "doomgeneric/mus2mid.h",
    "doomgeneric/net_client.h",
    "doomgeneric/net_dedicated.h",
    "doomgeneric/net_defs.h",
    "doomgeneric/net_gui.h",
    "doomgeneric/net_io.h",
    "doomgeneric/net_loop.h",
    "doomgeneric/net_packet.h",
    "doomgeneric/net_query.h",
    "doomgeneric/net_sdl.h",
    "doomgeneric/net_server.h",
    "doomgeneric/p_inter.h",
    "doomgeneric/p_local.h",
    "doomgeneric/p_mobj.h",
    "doomgeneric/p_pspr.h",
    "doomgeneric/p_saveg.h",
    "doomgeneric/p_setup.h",
    "doomgeneric/p_spec.h",
    "doomgeneric/p_tick.h",
    "doomgeneric/r_bsp.h",
    "doomgeneric/r_data.h",
    "doomgeneric/r_defs.h",
    "doomgeneric/r_draw.h",
    "doomgeneric/r_local.h",
    "doomgeneric/r_main.h",
    "doomgeneric/r_plane.h",
    "doomgeneric/r_segs.h",
    "doomgeneric/r_sky.h",
    "doomgeneric/r_state.h",
    "doomgeneric/r_things.h",
    "doomgeneric/sha1.h",
    "doomgeneric/sounds.h",
    "doomgeneric/s_sound.h",
    "doomgeneric/statdump.h",
    "doomgeneric/st_lib.h",
    "doomgeneric/st_stuff.h",
    "doomgeneric/tables.h",
    "doomgeneric/v_patch.h",
    "doomgeneric/v_video.h",
    "doomgeneric/w_checksum.h",
    "doomgeneric/w_file.h",
    "doomgeneric/wi_stuff.h",
    "doomgeneric/w_main.h",
    "doomgeneric/w_merge.h",
    "doomgeneric/w_wad.h",
    "doomgeneric/z_zone.h",
};
